engines:
  duplication:
  	enabled: true
    config:
    	languages:
      - javascript
ratings:
  paths:
  - src/**
  - spec/**

exclude_paths:
- spec/**/*
- "typings/**/*"
- node_modules/
- dist/
- coverage/