language: node_js
services: docker

sudo: false

node_js:
  - "6"

install:
  - npm install -g jasmine gulp typescript@1
  - npm install

env:
  - RABBITMQ_HOST=amqp://localhost:5672

before_script:
  - docker run -d -p 5672:5672 --name rabbitmq rabbitmq

script:
  - ISLAND_LOGGER_LEVEL=crit npm run coverage

after_script:
  - npm i coveralls && cat ./coverage/lcov-remap.info | coveralls
