language: node_js
services: docker

sudo: false

node_js:
  - "6"

install:
  - npm install -g jasmine gulp typescript
  - npm install

env:
  - RABBITMQ_HOST=amqp://localhost:5672

before_script:
  - docker run -d -p 5672:5672 --name rabbitmq rabbitmq

script:
  - gulp coverage

after_script:
  - npm i coveralls && cat ./coverage/lcov.info | coveralls